name: Check Stock Prices

on:
  schedule:
    # Runs every minute
    - cron: '* * * * *'

jobs:
  run-check:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger the price check URL
        run: curl https://your-app-name.onrender.com/trigger-check
